### ISSUE TITLE
More details to configure services.yaml

### ISSUE THREAD

**Issue by striker54** [ashald/home-assistant-lywsd02#1]
hello,
First of all, thanks for the hard work.
Can you give more detail on how to configure the service.yaml file.
    timestamp:
      description: Time to Set
      example: 1702200346
How is time coded in example? 

or can you make an example for the service.yaml to get the time that home assistant have in that moment?

best regards.

**Comment by 123Samy123** [comment]
Hey, i have the same question!

**Comment by ashald** [comment]
See [updated] [info.md](https://github.com/ashald/home-assistant-lywsd02/blob/main/info.md) for a usage example. Unless you don't get what you expect, you don't need to pass any parameters except the MAC address of the device. Also, updated docs in `services.yaml`.

**Comment by 123Samy123** [comment]
Thank you!
